"""Real-AI story branch exploration with durable V7 provenance.

The old implementation returned hard-coded examples from process memory and
reported successful apply/save operations without changing durable state. A
branch is now generated by the V7 gateway and stored as a ``v7_story_versions``
snapshot. Saving creates a real ``branch_draft`` content. Applying writes
through the canonical chapter content model with an optimistic concurrency
check, so a stale branch cannot overwrite newer editor work.
"""
from __future__ import annotations

import json
import math
import uuid
from datetime import datetime, timezone
from typing import Any

from fastapi import APIRouter, Depends, HTTPException, Request
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import get_current_user
from app.prompt_registry import sanitize_untrusted, untrusted_block

from ..db import get_async_db as get_db
from ..generation.generation_engine import AIGateway, AIGatewayError
from ...core.url_security import validate_ai_base_url
from ...services.novel_export import extract_body_text


# The parent router already supplies /branches.
router = APIRouter(tags=["v7-branches"])


def _parse_uuid(value: str, field: str) -> uuid.UUID:
    try:
        return uuid.UUID(str(value))
    except (TypeError, ValueError, AttributeError) as exc:
        raise HTTPException(status_code=400, detail=f"Invalid {field}") from exc


async def _load_scope(
    db: AsyncSession,
    novel_id: str,
    chapter_id: str,
    user: dict,
    *,
    write: bool = False,
) -> dict[str, Any]:
    """Resolve the chapter and enforce project membership in one query."""
    _parse_uuid(novel_id, "novel_id")
    _parse_uuid(chapter_id, "chapter_id")
    result = await db.execute(
        text(
            """
            SELECT c.id AS chapter_id, c.project_id, c.parent_id,
                   n.id AS novel_id, pm.role
            FROM contents c
            JOIN contents n ON n.id = c.parent_id
             AND n.id = :novel_id AND n.type = 'novel'
             AND n.is_deleted = FALSE
            JOIN project_members pm ON pm.project_id = c.project_id
             AND pm.user_id = :user_id
            WHERE c.id = :chapter_id AND c.type = 'chapter'
              AND c.is_deleted = FALSE
            LIMIT 1
            """
        ),
        {"novel_id": novel_id, "chapter_id": chapter_id, "user_id": user["id"]},
    )
    row = result.mappings().first()
    if not row:
        raise HTTPException(status_code=404, detail="chapter not found")
    if write and str(row["role"]) not in {"owner", "editor"}:
        raise HTTPException(status_code=403, detail="insufficient permissions")
    return dict(row)


def _normalise_options(raw: Any, expected: int) -> list[dict[str, Any]]:
    if not isinstance(raw, list) or not (2 <= len(raw) <= 4):
        raise AIGatewayError("branch provider output must contain 2-4 options")
    options: list[dict[str, Any]] = []
    for item in raw[:expected]:
        if not isinstance(item, dict):
            raise AIGatewayError("branch option is not an object")
        title = str(item.get("title") or "").strip()[:200]
        content = str(item.get("content") or "").strip()
        direction = str(item.get("direction") or "").strip()[:500]
        if len(title) < 2 or len(content) < 20 or len(direction) < 2:
            raise AIGatewayError("branch provider output is incomplete")
        try:
            confidence = float(item.get("confidence", 0.0))
        except (TypeError, ValueError):
            confidence = 0.0
        options.append(
            {
                "id": str(uuid.uuid4()),
                "title": title,
                "content": content,
                "direction": direction,
                "confidence": max(0.0, min(1.0, confidence)) if math.isfinite(confidence) else 0.0,
                "created_at": datetime.now(timezone.utc).isoformat(),
            }
        )
    if len(options) != expected:
        raise AIGatewayError("branch provider returned fewer options than requested")
    return options


def _snapshot_to_result(snapshot: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": snapshot["branch_id"],
        "novel_id": snapshot["novel_id"],
        "chapter_id": snapshot["chapter_id"],
        "source_text": snapshot["source_text"],
        "source_start": snapshot["source_start"],
        "source_end": snapshot["source_end"],
        "options": snapshot["options"],
        "status": snapshot.get("status", "completed"),
        "created_at": snapshot.get("created_at"),
    }


def _tiptap_body(text_value: str) -> dict[str, Any]:
    """Build the same denormalised TipTap shape used by the editor bridge."""
    paragraphs = [part.strip() for part in str(text_value or "").split("\n\n") if part.strip()]
    return {
        "type": "doc",
        "content": [
            {
                "type": "paragraph",
                "text": paragraph,
                "content": [{"type": "text", "text": paragraph}],
            }
            for paragraph in paragraphs
        ],
        "paragraphs": paragraphs,
        "text": "\n\n".join(paragraphs),
    }


def _apply_branch_text(
    current_text: str,
    source_text: str,
    source_start: int,
    source_end: int,
    replacement: str,
    mode: str,
) -> str:
    """Apply a branch only when its original selection still matches exactly."""
    if mode not in {"replace", "insert_after", "insert_before"}:
        raise HTTPException(status_code=422, detail="mode must be replace, insert_after, or insert_before")
    if source_start < 0 or source_end <= source_start or source_end > len(current_text):
        raise HTTPException(
            status_code=409,
            detail={
                "code": "BRANCH_SOURCE_CONFLICT",
                "message": "分支原文位置已失效，请重新生成分支",
            },
        )
    if current_text[source_start:source_end] != source_text:
        raise HTTPException(
            status_code=409,
            detail={
                "code": "BRANCH_SOURCE_CONFLICT",
                "message": "正文选区已变化，请重新生成分支",
            },
        )
    if mode == "replace":
        return current_text[:source_start] + replacement + current_text[source_end:]
    if mode == "insert_before":
        return current_text[:source_start] + replacement + "\n\n" + current_text[source_start:]
    return current_text[:source_end] + "\n\n" + replacement + current_text[source_end:]


async def _load_branch(db: AsyncSession, branch_id: str, user: dict, *, write: bool = False) -> dict[str, Any]:
    result = await db.execute(
        text(
            """
            SELECT snapshot_data
            FROM v7_story_versions
            WHERE version_type = 'branch'
              AND snapshot_data->>'branch_id' = :branch_id
            ORDER BY created_at DESC
            LIMIT 1
            """
        ),
        {"branch_id": branch_id},
    )
    row = result.mappings().first()
    if not row:
        raise HTTPException(status_code=404, detail="Branch not found")
    snapshot = row["snapshot_data"]
    if not isinstance(snapshot, dict):
        raise HTTPException(status_code=500, detail="branch snapshot is invalid")
    await _load_scope(db, snapshot["novel_id"], snapshot["chapter_id"], user, write=write)
    return snapshot


async def _store_branch(db: AsyncSession, snapshot: dict[str, Any], user_id: str) -> None:
    novel_id = _parse_uuid(snapshot["novel_id"], "novel_id")
    version_result = await db.execute(
        text(
            """
            SELECT COALESCE(MAX(version_number), 0) + 1
            FROM v7_story_versions
            WHERE novel_id = :novel_id
            """
        ),
        {"novel_id": novel_id},
    )
    version_number = int(version_result.scalar_one())
    await db.execute(
        text(
            """
            INSERT INTO v7_story_versions
                (id, novel_id, version_number, version_type, description,
                 snapshot_data, branch_name, created_by)
            VALUES
                (:id, :novel_id, :version_number, 'branch', :description,
                 CAST(:snapshot AS jsonb), 'exploration', :created_by)
            """
        ),
        {
            "id": uuid.uuid4(),
            "novel_id": novel_id,
            "version_number": version_number,
            "description": "AI 剧情分支探索",
            "snapshot": json.dumps(snapshot, ensure_ascii=False),
            "created_by": str(user_id),
        },
    )


def _gateway_for_request(request: Request, db: AsyncSession, scope: dict[str, Any]) -> AIGateway:
    api_key = request.headers.get("X-Api-Key", "").strip()
    base_url = request.headers.get("X-Api-Base-Url", "").strip()
    if base_url:
        if not api_key:
            raise HTTPException(status_code=400, detail="X-Api-Base-Url requires request-scoped X-Api-Key")
        try:
            base_url = validate_ai_base_url(base_url)
        except ValueError as exc:
            raise HTTPException(status_code=400, detail=str(exc)) from exc
    provider_config = {"api_key": api_key}
    if base_url:
        provider_config["base_url"] = base_url
    model = request.headers.get("X-Model", "").strip()
    if model:
        provider_config["model"] = model
    return AIGateway(
        db=db,
        novel_id=_parse_uuid(str(scope["novel_id"]), "novel_id"),
        project_id=str(scope["project_id"]),
        provider_config=provider_config,
    )


@router.post("/generate")
async def generate_branches(
    data: dict[str, Any],
    request: Request,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    novel_id = str(data.get("novel_id") or "")
    chapter_id = str(data.get("chapter_id") or "")
    source_text = str(data.get("source_text") or "").strip()
    if not novel_id or not chapter_id:
        raise HTTPException(status_code=400, detail="novel_id and chapter_id are required")
    if len(source_text) < 10 or len(source_text) > 12000:
        raise HTTPException(status_code=400, detail="source_text must contain 10-12000 characters")
    try:
        num_options = int(data.get("num_options", 3))
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail="num_options must be an integer") from exc
    if not 2 <= num_options <= 4:
        raise HTTPException(status_code=400, detail="num_options must be between 2 and 4")
    try:
        source_start = max(0, int(data.get("source_start", 0)))
        source_end = max(source_start, int(data.get("source_end", source_start)))
    except (TypeError, ValueError) as exc:
        raise HTTPException(status_code=400, detail="source range must be integers") from exc

    scope = await _load_scope(db, novel_id, chapter_id, user, write=True)
    context = sanitize_untrusted(data.get("context", ""), 8000)
    prompt = f"""
请为网文作者探索 {num_options} 条可直接写进正文的剧情分支，采用爽文节奏：主角主动出手，冲突升级快，每条路线都要有清晰的即时收益、代价和下一章钩子。
不要写创作建议，不要解释过程，不要复述输入。

{untrusted_block('选中的正文', source_text, 12000)}
{untrusted_block('已有上下文', context, 8000)}

只输出 JSON 对象，格式：
{{"options":[{{"title":"分支标题","direction":"走向、即时收益、代价和下一章钩子","content":"不少于 200 字的可直接使用正文","confidence":0.0}}]}}
options 必须恰好为 {num_options} 条；confidence 只是模型自评，不是事实概率。
"""
    try:
        generated = await _gateway_for_request(request, db, scope).generate_json(
            prompt,
            system_prompt="你是负责爽文剧情分叉的中文网文主笔，只输出合法 JSON。",
            temperature=0.95,
            max_tokens=7000,
            prompt_name="v7.plot.branch",
            prompt_version="1.0.0",
            task_type="generate_story_arc",
            client_mutation_id=str(data.get("client_mutation_id") or uuid.uuid4().hex),
        )
        options = _normalise_options(generated.get("data", {}).get("options"), num_options)
    except AIGatewayError as exc:
        raise HTTPException(
            status_code=502,
            detail={"code": "BRANCH_PROVIDER_FAILED", "message": "剧情分支生成失败，请稍后重试"},
        ) from exc

    now = datetime.now(timezone.utc).isoformat()
    snapshot = {
        "branch_id": str(uuid.uuid4()),
        "novel_id": novel_id,
        "chapter_id": chapter_id,
        "project_id": str(scope["project_id"]),
        "source_text": source_text,
        "source_start": source_start,
        "source_end": source_end,
        "options": options,
        "status": "completed",
        "created_at": now,
        "created_by": str(user["id"]),
    }
    await _store_branch(db, snapshot, str(user["id"]))
    return _snapshot_to_result(snapshot)


@router.get("/by-chapter/{chapter_id}")
async def list_chapter_branches(
    chapter_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    # Enforce membership even when the chapter has no stored branches.  The
    # previous loop-only check returned a successful empty list to outsiders.
    chapter_scope = await db.execute(
        text(
            """
            SELECT c.id AS chapter_id, c.project_id, c.parent_id,
                   n.id AS novel_id, pm.role
            FROM contents c
            JOIN contents n ON n.id = c.parent_id
             AND n.type = 'novel' AND n.is_deleted = FALSE
            JOIN project_members pm ON pm.project_id = c.project_id
             AND pm.user_id = :user_id
            WHERE c.id = :chapter_id AND c.type = 'chapter'
              AND c.is_deleted = FALSE
            LIMIT 1
            """
        ),
        {"chapter_id": chapter_id, "user_id": user["id"]},
    )
    if not chapter_scope.mappings().first():
        raise HTTPException(status_code=404, detail="chapter not found")
    result = await db.execute(
        text(
            """
            SELECT snapshot_data
            FROM v7_story_versions
            WHERE version_type = 'branch'
              AND snapshot_data->>'chapter_id' = :chapter_id
            ORDER BY created_at DESC
            """
        ),
        {"chapter_id": chapter_id},
    )
    items: list[dict[str, Any]] = []
    for row in result.mappings().all():
        snapshot = row["snapshot_data"]
        if isinstance(snapshot, dict):
            await _load_scope(db, snapshot["novel_id"], chapter_id, user)
            items.append(_snapshot_to_result(snapshot))
    return {"items": items, "total": len(items)}


@router.get("/stats/{novel_id}")
async def get_branch_stats(
    novel_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    scope_result = await db.execute(
        text("SELECT project_id FROM contents WHERE id=:novel_id AND type='novel' AND is_deleted=FALSE"),
        {"novel_id": novel_id},
    )
    scope = scope_result.mappings().first()
    if not scope:
        raise HTTPException(status_code=404, detail="novel not found")
    membership = await db.execute(
        text("SELECT role FROM project_members WHERE project_id=:project_id AND user_id=:user_id"),
        {"project_id": scope["project_id"], "user_id": user["id"]},
    )
    if not membership.mappings().first():
        raise HTTPException(status_code=403, detail="not a project member")
    rows = await db.execute(
        text(
            """
            SELECT snapshot_data
            FROM v7_story_versions
            WHERE version_type='branch' AND novel_id=:novel_id
            """
        ),
        {"novel_id": novel_id},
    )
    snapshots = [row["snapshot_data"] for row in rows.mappings().all()]
    total_options = sum(len(item.get("options", [])) for item in snapshots if isinstance(item, dict))
    return {
        "novel_id": novel_id,
        "total_generations": len(snapshots),
        "total_options": total_options,
        "avg_options_per_generation": total_options / len(snapshots) if snapshots else 0,
        "applied_count": sum(
            1 for item in snapshots
            if isinstance(item, dict) and item.get("status") == "applied"
        ),
        "saved_count": int((await db.execute(
            text(
                """
                SELECT COUNT(*)
                FROM contents
                WHERE project_id = :project_id AND type = 'branch_draft'
                  AND is_deleted = FALSE
                  AND meta->>'source' = 'v7_branch'
                  AND meta->>'branch_id' IN (
                      SELECT snapshot_data->>'branch_id'
                      FROM v7_story_versions
                      WHERE version_type = 'branch' AND novel_id = :novel_id
                  )
                """
            ),
            {"project_id": scope["project_id"], "novel_id": novel_id},
        )).scalar_one()),
    }


@router.get("/{branch_id}")
async def get_branch(
    branch_id: str,
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    return _snapshot_to_result(await _load_branch(db, branch_id, user))


@router.post("/{branch_id}/apply")
async def apply_branch(
    branch_id: str,
    data: dict[str, Any],
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    snapshot = await _load_branch(db, branch_id, user, write=True)
    option_id = str(data.get("option_id") or "")
    selected = next((option for option in snapshot.get("options", []) if option.get("id") == option_id), None)
    if selected is None:
        raise HTTPException(status_code=404, detail="Option not found")
    mode = str(data.get("mode") or "replace")
    if mode not in {"replace", "insert_after", "insert_before"}:
        raise HTTPException(status_code=422, detail="mode must be replace, insert_after, or insert_before")
    base_updated_at = data.get("base_updated_at")
    if not base_updated_at:
        raise HTTPException(
            status_code=422,
            detail={"code": "BRANCH_BASE_VERSION_REQUIRED", "message": "应用分支必须提供正文版本号"},
        )
    client_mutation_id = str(
        data.get("client_mutation_id")
        or f"branch:{branch_id}:{option_id}:{mode}"
    )[:100]

    # A repeated request must not create a second version or append the same
    # branch twice.  The editor uses a stable mutation id for this endpoint.
    replay = await db.execute(
        text(
            """
            SELECT c.body, c.updated_at
            FROM versions v
            JOIN contents c ON c.id = v.entity_id
            WHERE v.entity_type = 'content'
              AND v.reason = 'branch_apply'
              AND v.client_mutation_id = :client_mutation_id
            LIMIT 1
            """
        ),
        {"client_mutation_id": client_mutation_id},
    )
    replay_row = replay.mappings().first()
    if replay_row:
        return {
            "success": True,
            "replayed": True,
            "branch_id": branch_id,
            "option_id": option_id,
            "mode": mode,
            "chapter_id": snapshot["chapter_id"],
            "updated_at": replay_row["updated_at"].isoformat(),
            "applied_text": extract_body_text(replay_row["body"]),
        }

    chapter_result = await db.execute(
        text(
            """
            SELECT id, body, meta, updated_at
            FROM contents
            WHERE id = :chapter_id AND project_id = :project_id
              AND type = 'chapter' AND is_deleted = FALSE
            FOR UPDATE
            """
        ),
        {"chapter_id": snapshot["chapter_id"], "project_id": snapshot["project_id"]},
    )
    chapter = chapter_result.mappings().first()
    if not chapter:
        raise HTTPException(status_code=404, detail="chapter not found")
    try:
        requested_version = datetime.fromisoformat(str(base_updated_at).replace("Z", "+00:00"))
    except ValueError as exc:
        raise HTTPException(status_code=422, detail="base_updated_at must be an ISO timestamp") from exc
    current_version = chapter["updated_at"]
    if current_version.tzinfo is None:
        current_version = current_version.replace(tzinfo=timezone.utc)
    if requested_version.astimezone(timezone.utc) != current_version.astimezone(timezone.utc):
        raise HTTPException(
            status_code=409,
            detail={
                "code": "BRANCH_VERSION_CONFLICT",
                "message": "正文在分支生成后已被修改，请重新生成或先合并当前编辑内容",
                "current_updated_at": current_version.isoformat(),
            },
        )

    current_text = extract_body_text(chapter["body"])
    applied_text = _apply_branch_text(
        current_text,
        str(snapshot.get("source_text") or ""),
        int(snapshot.get("source_start", 0)),
        int(snapshot.get("source_end", 0)),
        str(selected["content"]),
        mode,
    )
    meta = chapter["meta"] if isinstance(chapter["meta"], dict) else {}
    apply_log = list(meta.get("branch_apply_log") or [])
    apply_log.append({
        "branch_id": branch_id,
        "option_id": option_id,
        "mode": mode,
        "base_updated_at": current_version.isoformat(),
        "applied_at": datetime.now(timezone.utc).isoformat(),
    })
    next_meta = {**meta, "branch_apply_log": apply_log}
    previous_version = await db.execute(
        text(
            """
            SELECT id FROM versions
            WHERE entity_type = 'content' AND entity_id = :chapter_id
            ORDER BY created_at DESC LIMIT 1
            """
        ),
        {"chapter_id": snapshot["chapter_id"]},
    )
    parent_version_id = previous_version.scalar_one_or_none()
    await db.execute(
        text(
            """
            INSERT INTO versions
                (id, entity_type, entity_id, parent_version_id, label, snapshot,
                 reason, author_id, client_mutation_id)
            VALUES
                (:id, 'content', :entity_id, :parent_version_id, 'branch_apply',
                 CAST(:snapshot AS jsonb), 'branch_apply', :author_id, :client_mutation_id)
            """
        ),
        {
            "id": uuid.uuid4(),
            "entity_id": snapshot["chapter_id"],
            "parent_version_id": parent_version_id,
            "snapshot": json.dumps(
                {"body": chapter["body"], "meta": chapter["meta"], "source": "v7_branch"},
                ensure_ascii=False,
            ),
            "author_id": user["id"],
            "client_mutation_id": client_mutation_id,
        },
    )
    updated = await db.execute(
        text(
            """
            UPDATE contents
            SET body = CAST(:body AS jsonb), meta = CAST(:meta AS jsonb),
                status = 'draft', updated_at = now()
            WHERE id = :chapter_id
            RETURNING updated_at
            """
        ),
        {
            "body": json.dumps(_tiptap_body(applied_text), ensure_ascii=False),
            "meta": json.dumps(next_meta, ensure_ascii=False),
            "chapter_id": snapshot["chapter_id"],
        },
    )
    updated_at = updated.scalar_one()
    await db.execute(
        text(
            """
            UPDATE v7_story_versions
            SET snapshot_data = snapshot_data || CAST(:patch AS jsonb)
            WHERE version_type = 'branch'
              AND snapshot_data->>'branch_id' = :branch_id
            """
        ),
        {
            "branch_id": branch_id,
            "patch": json.dumps(
                {
                    "status": "applied",
                    "applied_option_id": option_id,
                    "applied_mode": mode,
                    "applied_at": datetime.now(timezone.utc).isoformat(),
                },
                ensure_ascii=False,
            ),
        },
    )
    return {
        "success": True,
        "replayed": False,
        "branch_id": branch_id,
        "option_id": option_id,
        "mode": mode,
        "chapter_id": snapshot["chapter_id"],
        "updated_at": updated_at.isoformat(),
        "applied_text": applied_text,
    }


@router.post("/{branch_id}/save")
async def save_branch(
    branch_id: str,
    data: dict[str, Any],
    user: dict = Depends(get_current_user),
    db: AsyncSession = Depends(get_db),
):
    snapshot = await _load_branch(db, branch_id, user, write=True)
    option_id = str(data.get("option_id") or "")
    selected = next((option for option in snapshot.get("options", []) if option.get("id") == option_id), None)
    if selected is None:
        raise HTTPException(status_code=404, detail="Option not found")
    title = str(data.get("title") or selected["title"]).strip()[:200]
    notes = sanitize_untrusted(data.get("notes", ""), 2000)
    draft_id = uuid.uuid4()
    await db.execute(
        text(
            """
            INSERT INTO contents
                (id, project_id, parent_id, type, title, body, meta, status, owner_id)
            VALUES
                (:id, :project_id, :parent_id, 'branch_draft', :title,
                 CAST(:body AS jsonb), CAST(:meta AS jsonb), 'draft', :owner_id)
            """
        ),
        {
            "id": draft_id,
            "project_id": _parse_uuid(str(snapshot["project_id"]), "project_id"),
            "parent_id": _parse_uuid(str(snapshot["chapter_id"]), "chapter_id"),
            "title": title,
            "body": json.dumps({"text": selected["content"]}, ensure_ascii=False),
            "meta": json.dumps(
                {"branch_id": branch_id, "option_id": option_id, "notes": notes, "source": "v7_branch"},
                ensure_ascii=False,
            ),
            "owner_id": user["id"],
        },
    )
    return {
        "success": True,
        "draft_id": str(draft_id),
        "branch_id": branch_id,
        "option_id": option_id,
        "saved_title": title,
        "saved_content": selected["content"],
        "notes": notes,
    }
