#!/bin/bash
# Generated by Hermes — do not commit
TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4OTBlNzdiNC0wYmE1LTRkMWQtYWZkMy1iYWFjODYyMmYyZDMiLCJleHAiOjE3NzIzMjgzMjF9.Y7Nj8leIty2g9MBiaFRqE68qL4wriGTGY8-1BFshGqQ"
NOVEL="80b4c606-e601-4182-a9be-99d6d4cdad09"
PROJ_ID="da83757e-005e-4543-8cee-c0d294f31a47"
API="http://localhost:8100/api/v1"
